run:
	@g++ myTests.cpp
	@./a.out

iterator:
	@g++ tests_iterator.cpp
	@./a.out

list:
	@g++ main.cc s21_list.cc s21_list.h
	@./a.out

initialization_list:
	@g++ tests_initialization_list.cpp
	@./a.out