name: Containers

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev

    - name: Build project
      run: |
        cd src
        make build

  style-check:
    name: Check code style
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0

    - name: Check code style
      run: |
        cd src
        make style-check

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y check libsubunit-dev libgtest-dev

    - name: Run unit tests
      run: |
        cd src
        make build
        make test

  gcov-report:
    name: Generate code coverage report
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y check libsubunit-dev lcov libgtest-dev

    - name: Generate code coverage report
      run: |
        cd src
        make build
        make test
        make gcov_report

  valgrind-test:
    name: Run Valgrind test
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y check libsubunit-dev valgrind libgtest-dev

    - name: Run Valgrind test
      run: |
        cd src
        make build
        make test
        make valgrind
